[2024-09-01T15:18:09.087+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-01T15:18:09.109+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_airbnb_etl.write_data manual__2024-09-01T15:17:57+00:00 [queued]>
[2024-09-01T15:18:09.119+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_airbnb_etl.write_data manual__2024-09-01T15:17:57+00:00 [queued]>
[2024-09-01T15:18:09.120+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-01T15:18:09.136+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): write_data> on 2024-09-01 15:17:57+00:00
[2024-09-01T15:18:09.145+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=149) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T15:18:09.147+0000] {standard_task_runner.py:72} INFO - Started process 158 to run task
[2024-09-01T15:18:09.147+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nyc_airbnb_etl', 'write_data', 'manual__2024-09-01T15:17:57+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/nyc_airbnb_etl.py', '--cfg-path', '/tmp/tmpamhhtlxl']
[2024-09-01T15:18:09.149+0000] {standard_task_runner.py:105} INFO - Job 218: Subtask write_data
[2024-09-01T15:18:09.202+0000] {task_command.py:467} INFO - Running <TaskInstance: nyc_airbnb_etl.write_data manual__2024-09-01T15:17:57+00:00 [running]> on host b74353bc56c3
[2024-09-01T15:18:09.308+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_airbnb_etl' AIRFLOW_CTX_TASK_ID='write_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T15:17:57+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T15:17:57+00:00'
[2024-09-01T15:18:09.310+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-01T15:18:09.310+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-01T15:18:09.311+0000] {logging_mixin.py:190} INFO - Current task name:write_data state:running start_date:2024-09-01 15:18:09.109697+00:00
[2024-09-01T15:18:09.311+0000] {logging_mixin.py:190} INFO - Dag name:nyc_airbnb_etl and current dag run status:running
[2024-09-01T15:18:09.312+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-01T15:18:09.312+0000] {sql.py:282} INFO - Executing: 
            COPY airbnb_listings FROM '/transformed/transformed/ab_nyc.csv'
            DELIMITER ','
            CSV HEADER;
        
[2024-09-01T15:18:09.322+0000] {base.py:84} INFO - Retrieving connection 'test-connection'
[2024-09-01T15:18:09.333+0000] {base.py:84} INFO - Retrieving connection 'test-connection'
[2024-09-01T15:18:09.348+0000] {sql.py:509} INFO - Running statement: 
            COPY airbnb_listings FROM '/transformed/transformed/ab_nyc.csv'
            DELIMITER ','
            CSV HEADER;
        , parameters: None
[2024-09-01T15:18:09.374+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "airbnb_listings_pkey"
DETAIL:  Key (id)=(2539) already exists.
CONTEXT:  COPY airbnb_listings, line 2

[2024-09-01T15:18:09.387+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-01T15:18:09.387+0000] {logging_mixin.py:190} INFO - Task start:2024-09-01 15:18:09.109697+00:00 end:2024-09-01 15:18:09.386419+00:00 duration:0.276722
[2024-09-01T15:18:09.388+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): write_data> dag:<DAG: nyc_airbnb_etl> dagrun:<DagRun nyc_airbnb_etl @ 2024-09-01 15:17:57+00:00: manual__2024-09-01T15:17:57+00:00, state:running, queued_at: 2024-09-01 15:17:58.781598+00:00. externally triggered: True>
[2024-09-01T15:18:09.388+0000] {logging_mixin.py:190} INFO - Failure caused by duplicate key value violates unique constraint "airbnb_listings_pkey"
DETAIL:  Key (id)=(2539) already exists.
CONTEXT:  COPY airbnb_listings, line 2
[2024-09-01T15:18:09.389+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=nyc_airbnb_etl, task_id=write_data, run_id=manual__2024-09-01T15:17:57+00:00, execution_date=20240901T151757, start_date=20240901T151809, end_date=20240901T151809
[2024-09-01T15:18:09.405+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-01T15:18:09.406+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 218 for task write_data (duplicate key value violates unique constraint "airbnb_listings_pkey"
DETAIL:  Key (id)=(2539) already exists.
CONTEXT:  COPY airbnb_listings, line 2
; 158)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "airbnb_listings_pkey"
DETAIL:  Key (id)=(2539) already exists.
CONTEXT:  COPY airbnb_listings, line 2

[2024-09-01T15:18:09.443+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-01T15:18:09.456+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-09-01T15:18:09.466+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-01T15:18:09.469+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
